#!/usr/bin/env bash

# Copyright © 2020-2024 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

normspace()
{
    local s
    # shellcheck disable=SC2048,SC2086
    s=$(set -f; printf '%s ' $*)
    printf '%s' "${s% }"
}

user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0'
tmpfile=$(mktemp -t strixaluco.XXXXXX)
sep=''
for url in "$@"
do
    curl --silent --fail --show-error --location --user-agent "$user_agent" "$url" > "$tmpfile"
    title=$(hxextract .desc-o-mb-title "$tmpfile")
    title=$(hxselect -c span <<< "$title")
    title=$(normspace "$title")
    rest=$(hxextract .desc-o-b-rest "$tmpfile")
    rest=$(hxselect -c span <<< "$rest")
    rest=$(normspace "$rest")
    rest=${rest#/ }
    printf '%s"%s" %s\n' "$sep" "$title" "$rest"
    printf '%s\n' "$url"
    sep=$'\n'
done
rm -f "$tmpfile"

# vim:ts=4 sts=4 sw=4 et
