#!/usr/bin/env bash

# Copyright © 2020-2026 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

normspace()
{
    local s
    # shellcheck disable=SC2048,SC2086
    s=$(set -f; printf '%s ' $*)
    printf '%s' "${s% }"
}

user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:140.0) Gecko/20100101 Firefox/140.0'
sep=''
if [ $# -eq 0 ] && ! [ -t 0 ]
then
    set -f
    # shellcheck disable=SC2046
    set -- $(cat)
    set +f
fi
for url in "$@"
do
    html=$(curl --silent --fail --show-error --location --user-agent "$user_agent" "$url")
    title=$(pup '.desc-o-mb-title text{}' <<< "$html")
    title=$(normspace "$title")
    rest=$(pup '.desc-o-b-rest text{}' <<< "$html")
    rest=$(normspace "$rest")
    rest=${rest#/ }
    printf '%s"%s" %s\n' "$sep" "$title" "$rest"
    printf '%s\n' "$url"
    sep=$'\n'
done

# vim:ts=4 sts=4 sw=4 et
